# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionTurnos', '0004_auto_20161006_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='duracion',
            field=models.TimeField(default=datetime.datetime(2016, 10, 11, 0, 0)),
        ),
    ]
